In [ ]:
"""1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

arr

array([0, 1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int32')

In [ ]:
"""2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [6]:
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [ ]:
"""3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [7]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [ ]:
"""4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

arr_float = arr.astype(np.float32)

arr

array([1, 2, 3, 4, 5])

In [9]:
arr_float.dtype

dtype('float32')

In [ ]:
"""5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [10]:
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

arr

array([1.12345679, 2.98765432, 3.45678912])

In [11]:
arr.dtype

dtype('float64')

In [12]:
arr_float

dtype('float32')

In [ ]:
"""6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [13]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)

print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])

Shape: (2, 3)
Size: 6
Data type: int32


In [ ]:
"""7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [14]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print("Dimensionality:", dimension)

Dimensionality: 2


In [ ]:
"""8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [15]:
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
  
    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 4
Total size (bytes): 24


In [ ]:
"""9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [16]:
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)

Strides: (12, 4)


In [ ]:
"""10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [17]:
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    
    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


In [ ]:
"""11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements

In [18]:
def create_zeros_array(n):
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)

Array of zeros: [0. 0. 0. 0. 0.]


In [ ]:
"""12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [19]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("2D array of ones:\n", ones_matrix)

2D array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
"""13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [20]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)

Range array: [1 3 5 7 9]


In [ ]:
"""14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [21]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)

Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
"""15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [22]:
def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
"""16. Write a function that takes a Python list and converts it into a NumPy array.

In [25]:
def list_to_array(py_list):
    return np.array(py_list)

py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_array(py_list)

print("NumPy array:", numpy_array)

NumPy array: [1 2 3 4 5]


In [ ]:
"""17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [28]:
array = np.array([[1, 2, 3], [4, 5, 6]])

view_array = array.view()

view_array[0, 0] = 10

print("Original array:\n", array)
print("View array:\n", view_array)

Original array:
 [[10  2  3]
 [ 4  5  6]]
View array:
 [[10  2  3]
 [ 4  5  6]]


In [ ]:
"""18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [29]:
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)

print("Concatenated along axis 0:\n", concatenated_array_axis0)

Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
"""19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
concatenate`.

In [30]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Concatenated array:\n", concatenated_array)

Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
"""20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [31]:
def vertical_stack_arrays(arrays):
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

arrays = [array1, array2, array3]
stacked_array = vertical_stack_arrays(arrays)

print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
"""21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [32]:
def create_range_array(start, stop, step):
    return np.arange(start, stop + step, step)

start = 1
stop = 10
step = 2
range_array = create_range_array(start, stop, step)

print("Range array:", range_array)

Range array: [ 1  3  5  7  9 11]


In [ ]:
"""22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [33]:
def generate_equally_spaced_values(num_values):
    return np.linspace(0, 1, num=num_values)

num_values = 10
values_array = generate_equally_spaced_values(num_values)

print("Array of equally spaced values:", values_array)

Array of equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
"""23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [34]:
import numpy as np

def generate_logarithmically_spaced_values(num_values):
    return np.logspace(np.log10(1), np.log10(1000), num=num_values)

num_values = 5
log_values_array = generate_logarithmically_spaced_values(num_values)

print("Array of logarithmically spaced values:", log_values_array)

Array of logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
"""24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [35]:
import pandas as pd

data = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print("DataFrame:\n", df)

DataFrame:
    Column1  Column2  Column3
0       86       99       28
1       13       30       25
2       18       58       80
3       33       18       58
4       27       52       41


In [ ]:
"""25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [36]:
def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [10, -5, 3, -1, 4], 'B': [-7, 2, -8, 5, 6]}
df = pd.DataFrame(data)

df_updated = replace_negatives_with_zeros(df, 'A')

print("Updated DataFrame:\n", df_updated)

Updated DataFrame:
     A  B
0  10 -7
1   0  2
2   3 -8
3   0  5
4   4  6


In [ ]:
"""26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [37]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [ ]:
"""27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [38]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [ ]:
"""28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [39]:
arr = np.array([3, 8, 2, 10, 5, 7])

mask = arr > 5

filtered_elements = arr[mask]

print("Elements greater than 5:", filtered_elements)

Elements greater than 5: [ 8 10  7]


In [ ]:
"""29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
"""30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [41]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
"""31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [42]:
def extract_elements_based_on_indices(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 1],  
                    [1, 2], 
                    [2, 0]]) 

extracted_elements = extract_elements_based_on_indices(arr_2d, indices)

print("Extracted elements:", extracted_elements)

Extracted elements: [20 60 70]


In [ ]:
"""32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [43]:
def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([5, 12, 7, 3, 18, 9])
threshold = 10

filtered_elements = filter_elements_greater_than_threshold(arr, threshold)

print("Filtered elements:", filtered_elements)

Filtered elements: [12 18]


In [ ]:
"""33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [44]:
def extract_elements_from_3d_array(arr_3d, indices_x, indices_y, indices_z):
    return arr_3d[indices_x, indices_y, indices_z]

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

indices_x = np.array([0, 1, 2])
indices_y = np.array([0, 1, 2])
indices_z = np.array([2, 1, 0])

extracted_elements = extract_elements_from_3d_array(arr_3d, indices_x, indices_y, indices_z)

print("Extracted elements:", extracted_elements)

Extracted elements: [ 3 14 25]


In [ ]:
"""34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [45]:
def filter_elements_with_conditions(arr, condition1, condition2):
    return arr[condition1 & condition2]

arr = np.array([10, 15, 20, 25, 30, 35, 40])

condition1 = arr > 15  
condition2 = arr % 10 == 0 

filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)

print("Filtered elements :", filtered_elements)

Filtered elements : [20 30 40]


In [ ]:
"""35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [46]:
def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])


extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)

print("Extracted elements:", extracted_elements)

Extracted elements: [20 60 70]


In [ ]:
"""36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print("Array:\n", result)

Array:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
"""37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [49]:
arr1 = np.array([[2, 3, 4]]) 
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  

arr1_reshaped = arr1.T  

result = arr2 * arr1_reshaped

print("Result of multiplying each row of arr2 by arr1:\n", result)

Result of multiplying each row of arr2 by arr1:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [ ]:
"""38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [50]:
arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  

arr1_reshaped = np.broadcast_to(arr1[:, :3], arr2.shape)  

result = arr2 + arr1_reshaped

print("Result:\n", result)

Result:
 [[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


In [ ]:
"""39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [51]:
arr1 = np.array([[1],
                 [2],
                 [3]]) 

arr2 = np.array([[10, 20, 30]])  

result = arr1 + arr2

print("Result :\n", result)

Result :
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
"""40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [53]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]]) 

arr2 = np.array([[7, 8],
                 [9, 10]])  

arr1_trimmed = arr1[:, :2] 

result = arr1_trimmed * arr2

print("Result :\n", result)

Result :
 [[ 7 16]
 [36 50]]


In [ ]:
"""41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.mean(arr,axis=0)
arr1

array([2.5, 3.5, 4.5])

In [ ]:
"""42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)

array([3, 6])

In [ ]:
"""43. For the given array, find indices of maximum value in each column
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr, axis=0)

array([1, 1, 1], dtype=int64)

In [ ]:
"""44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [63]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])


window_size = 2

moving_sums = np.array([np.convolve(row, np.ones(window_size, dtype=int), mode='valid') for row in arr])

print("Moving sum along rows:\n", moving_sums)

Moving sum along rows:
 [[ 3  5]
 [ 9 11]]


In [ ]:
"""45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [64]:
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

are_all_even = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even", are_all_even)

Are all elements in each column even [False False False]


In [ ]:
"""46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3  

reshaped_matrix = original_array.reshape(m, n)

print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
"""47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
"""48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [4]:
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis0)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
"""49. Create a function that splits an array into multiple sub-arrays along a specified axis
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
def split_array(array, num_splits, axis):
    return np.array_split(array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_axis0 = split_array(original_array, num_splits=3, axis=0)
print("Split along axis 0:\n", split_axis0)

Split along axis 0:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
"""50. Write a function that inserts and then deletes elements from a given array at specified indices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [6]:
def insert_and_delete(array, insert_indices, insert_values, delete_indices):
    insert_indices = sorted(insert_indices)
    

    for idx, value in zip(insert_indices, insert_values):
        array = np.insert(array, idx, value)
    
    
    for idx in sorted(delete_indices, reverse=True):
        array = np.delete(array, idx)
    
    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified array:", modified_array)

Modified array: [ 1 10 11  4  5]


In [ ]:
"""51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [7]:
arr1 = np.random.randint(0, 10, size=(3, 4))  
print("arr1:\n", arr1)

arr2 = np.arange(1, 11).reshape(2, 5) 
print("arr2:\n", arr2)

arr2_resized = np.resize(arr2, arr1.shape)  
print("arr2 resized:\n", arr2_resized)


result = arr1 + arr2_resized
print("Result of element-wise addition:\n", result)

arr1:
 [[5 2 2 8]
 [5 5 9 8]
 [4 6 3 7]]
arr2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr2 resized:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1  2]]
Result of element-wise addition:
 [[ 6  4  5 12]
 [10 11 16 16]
 [13 16  4  9]]


In [ ]:
"""52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [8]:
arr1 = np.arange(10, 0, -1) 
print("arr1:\n", arr1)

arr2 = np.arange(1, 11)  
print("arr2:\n", arr2)

result = arr1 - arr2
print("Result of element-wise subtraction:\n", result)

arr1:
 [10  9  8  7  6  5  4  3  2  1]
arr2:
 [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction:
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
"""53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [9]:
arr1 = np.random.randint(1, 10, size=(3, 4)) 
print("arr1:\n", arr1)

arr2 = np.array([1, 2, 3, 4]) 
print("arr2:\n", arr2)

arr2_resized = np.tile(arr2, (arr1.shape[0], 1))  
print("arr2 resized:\n", arr2_resized)

result = arr1 * arr2_resized
print("Result of element-wise multiplication:\n", result)

arr1:
 [[2 5 6 7]
 [1 9 1 1]
 [7 7 6 6]]
arr2:
 [1 2 3 4]
arr2 resized:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
Result of element-wise multiplication:
 [[ 2 10 18 28]
 [ 1 18  3  4]
 [ 7 14 18 24]]


In [ ]:
"""54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [10]:
arr1 = np.arange(2, 11, 2)
print("arr1:\n", arr1)

arr2 = np.array([1, 2, 3, 4, 5]) 
print("arr2:\n", arr2)

result = arr1 / arr2
print("Result of element-wise division:\n", result)

arr1:
 [ 2  4  6  8 10]
arr2:
 [1 2 3 4 5]
Result of element-wise division:
 [2. 2. 2. 2. 2.]


In [ ]:
"""55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [11]:
arr1 = np.array([1, 2, 3, 4, 5])
print("arr1:\n", arr1)

arr2 = arr1[::-1] 
print("arr2:\n", arr2)

result = np.power(arr1, arr2)
print("Result of element-wise exponentiation:\n", result)

arr1:
 [1 2 3 4 5]
arr2:
 [5 4 3 2 1]
Result of element-wise exponentiation:
 [ 1 16 27 16  5]


In [ ]:
"""56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [12]:
def count_substring_occurrences(array, substring):
    return np.sum(np.char.find(array, substring) != -1)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

substring = 'hello'

count = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}':", count)

Occurrences of 'hello': 3


In [ ]:
"""57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [13]:
def extract_uppercase(array):
    flattened_array = array.flatten()
    
    uppercase_chars = [char for string in flattened_array for char in string if char.isupper()]
    
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
print("Uppercase characters:", result)

Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [ ]:
"""58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [14]:
def replace_substring(array, old_substring, new_string):
    replaced_array = np.char.replace(array, old_substring, new_string)
    
    return replaced_array

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

old_substring = 'apple'
new_string = 'orange'

result = replace_substring(arr, old_substring, new_string)
print("Array after replacement:\n", result)

Array after replacement:
 ['orange' 'banana' 'grape' 'pineorange']


In [ ]:
"""59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [15]:
def concatenate_strings(arr1, arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("Both arrays must have the same shape for element-wise concatenation.")
    
    concatenated_array = np.char.add(arr1, arr2)
    
    return concatenated_array

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print("Concatenated array:\n", result)

Concatenated array:
 ['HelloOpen' 'WorldAI']


In [ ]:
"""60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [16]:
def longest_string_length(array):
    lengths = np.char.str_len(array)
    
    max_length = np.max(lengths)
    
    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)
print("Length of the longest string:", result)

Length of the longest string: 9


In [ ]:
"""61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [17]:
dataset = np.random.randint(1, 1001, size=100)
print("Dataset:\n", dataset)

mean_value = np.mean(dataset)
print("Mean:", mean_value)

median_value = np.median(dataset)
print("Median:", median_value)

variance_value = np.var(dataset, ddof=0)  
print("Variance:", variance_value)

std_dev_value = np.std(dataset, ddof=0)  
print("Standard Deviation:", std_dev_value)

Dataset:
 [642 181 417 445 717  95 880 268 803 202 921 944 683  93  26  92 148 632
  38 230 323 936 464  85 582 640 894 852 494 228 278 182  36 153 295 859
 408 867 542 102 505 793 312 185 645 843 559 946 959 637 477 549 729 469
 568 918 554 306 319 774 631 876 820 368 335 966 262 968 316 398 981  34
 453 334 288 140 532 702 215 966 498 158 354 847 182 138 922  13 277 630
 520 101 808  43 298 165 193 806 361 338]
Mean: 479.61
Median: 458.5
Variance: 86405.8579
Standard Deviation: 293.9487334553425


In [ ]:
"""62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [18]:
dataset = np.random.randint(1, 101, size=50)
print("Dataset:\n", dataset)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset:
 [ 59  49  22  60  95  17  23  97  28  51  79  33  73  88  46  28  67 100
  95  31  19  36  21  59  99  66  80  44  29  28  43  73  35  63  55  32
  90  74  67  50  68  10  61  30  31   5  78  44  70  88]
25th Percentile: 31.0
75th Percentile: 73.0


In [ ]:
"""63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [19]:
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([5, 15, 25, 35, 45])

correlation_matrix = np.corrcoef(array1, array2)

correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Matrix:\n", correlation_matrix)
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)

Correlation Matrix:
 [[1. 1.]
 [1. 1.]]
Correlation Coefficient between array1 and array2: 1.0


In [ ]:
"""64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [20]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Result of Matrix Multiplication:
 [[19 22]
 [43 50]]


In [ ]:
"""65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [21]:
array = np.random.randint(10, 1001, size=50)
print("Array:\n", array)

percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)  
percentile_90 = np.percentile(array, 90)

first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)

Array:
 [270 651 593 369  90  86  87 519  70 481 832 584  11 637  45  46 554 420
 422 143 545 569 905  39 484 999 932 204 262 491 644 467 898 353 842 962
 714 611 955 422  21 714  24  39 893  96 863 141 893 809]
10th Percentile: 44.400000000000006
50th Percentile (Median): 487.5
90th Percentile: 898.7
First Quartile (25th Percentile): 141.5
Third Quartile (75th Percentile): 714.0


In [ ]:
"""66. Create a NumPy array of integers and find the index of a specific element.

In [22]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

element_to_find = 50

indices = np.where(array == element_to_find)

index_list = indices[0].tolist()


if index_list:
    print(f"The index of element {element_to_find} is: {index_list}")
else:
    print(f"Element {element_to_find} is not found in the array.")

The index of element 50 is: [4]


In [ ]:
"""67. Generate a random NumPy array and sort it in ascending order.

In [23]:
random_array = np.random.randint(1, 101, size=10)
print("Random Array:\n", random_array)

sorted_array = np.sort(random_array)
print("Sorted Array:\n", sorted_array)

Random Array:
 [87 90 69 65 12 50 71  2 56 25]
Sorted Array:
 [ 2 12 25 50 56 65 69 71 87 90]


In [ ]:
"""68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [24]:
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original Array:\n", arr)
print("Filtered Array (elements > 20):\n", filtered_arr)

Original Array:
 [12 25  6 42  8 30]
Filtered Array (elements > 20):
 [25 42 30]


In [ ]:
"""69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [25]:
arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("Original Array:\n", arr)
print("Filtered Array (elements divisible by 3):\n", filtered_arr)

Original Array:
 [ 1  5  8 12 15]
Filtered Array (elements divisible by 3):
 [12 15]


In [ ]:
"""70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [26]:
arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:\n", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):\n", filtered_arr)

Original Array:
 [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40):
 [20 30 40]


In [ ]:
"""71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])

In [27]:
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

if byte_order == '>':
    byte_order_str = 'Big-endian'
elif byte_order == '<':
    byte_order_str = 'Little-endian'
elif byte_order == '=':
    byte_order_str = 'Native endian'
else:
    byte_order_str = 'Unknown'

print("Byte Order:", byte_order_str)

Byte Order: Native endian


In [ ]:
"""72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:\n", arr)

arr.byteswap(inplace=True)
print("Array After Byte Swapping:\n", arr)

Original Array:
 [1 2 3]
Array After Byte Swapping:
 [16777216 33554432 50331648]


In [ ]:
"""73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:\n", arr)

swapped_arr = arr.newbyteorder()
print("Array with Swapped Byte Order:\n", swapped_arr)

Original Array:
 [1 2 3]
Array with Swapped Byte Order:
 [16777216 33554432 50331648]


In [ ]:
"""74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:\n", arr)

system_byte_order = np.dtype(np.int32).byteorder

if system_byte_order == '<':  
    target_byte_order = '>'
elif system_byte_order == '>':  
    target_byte_order = '<'
else:
    target_byte_order = '='  

swapped_arr = arr.newbyteorder(target_byte_order)
print("Array with Conditioned Byte Order:\n", swapped_arr)

Original Array:
 [1 2 3]
Array with Conditioned Byte Order:
 [1 2 3]


In [ ]:
"""75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder
arr = np.array([1, 2, 3], dtype=np.int32)

In [31]:
arr = np.array([1, 2, 3], dtype=np.int32)

system_byte_order = np.dtype(np.int32).byteorder

array_byte_order = arr.dtype.byteorder

if array_byte_order == system_byte_order:
    print("Byte swapping is not necessary. Array byte order matches system byte order.")
else:
    print("Byte swapping is necessary. Array byte order differs from system byte order.")

Byte swapping is not necessary. Array byte order matches system byte order.


In [ ]:
"""76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [32]:
arr1 = np.arange(1, 11)
print("Original Array (arr1):\n", arr1)

copy_arr = arr1.copy()
print("Copied Array (copy_arr):\n", copy_arr)

copy_arr[0] = 100
print("Modified Copied Array (copy_arr):\n", copy_arr)

print("Original Array After Modification (arr1):\n", arr1)

Original Array (arr1):
 [ 1  2  3  4  5  6  7  8  9 10]
Copied Array (copy_arr):
 [ 1  2  3  4  5  6  7  8  9 10]
Modified Copied Array (copy_arr):
 [100   2   3   4   5   6   7   8   9  10]
Original Array After Modification (arr1):
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
"""78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [33]:
array_a = np.arange(1, 13).reshape(4, 3)
print("Original Array (array_a):\n", array_a)

view_b = array_a[1:3, 1:3]
print("View (view_b):\n", view_b)

view_b += 5
print("Modified View (view_b):\n", view_b)

print("Original Array After Modification (array_a):\n", array_a)

Original Array (array_a):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View (view_b):
 [[5 6]
 [8 9]]
Modified View (view_b):
 [[10 11]
 [13 14]]
Original Array After Modification (array_a):
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [ ]:
"""79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`."""

In [34]:
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original Array (orig_array):\n", orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("Reshaped View (reshaped_view):\n", reshaped_view)

reshaped_view[1, 0] = 99
print("Modified Reshaped View (reshaped_view):\n", reshaped_view)

print("Original Array After Modification (orig_array):\n", orig_array)

Original Array (orig_array):
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped View (reshaped_view):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified Reshaped View (reshaped_view):
 [[ 1  2]
 [99  4]
 [ 5  6]
 [ 7  8]]
Original Array After Modification (orig_array):
 [[ 1  2 99  4]
 [ 5  6  7  8]]


In [ ]:
"""80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [35]:
np.random.seed(0) 
data = np.random.randint(1, 10, size=(3, 4))
print("Original Data (data):\n", data)

data_copy = data[data > 5].copy()
print("Copy of Elements Greater Than 5 (data_copy):\n", data_copy)

data_copy[0] = 99
print("Modified Copy (data_copy):\n", data_copy)

print("Original Data After Modification (data):\n", data)

Original Data (data):
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
Copy of Elements Greater Than 5 (data_copy):
 [6 8 6 8 7 9]
Modified Copy (data_copy):
 [99  8  6  8  7  9]
Original Data After Modification (data):
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]


In [ ]:
"""81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them

In [36]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

addition_result = A + B
subtraction_result = A - B

print("Addition Result (A + B):\n", addition_result)
print("Subtraction Result (A - B):\n", subtraction_result)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Addition Result (A + B):
 [[ 8 10 12]
 [14 16 18]]
Subtraction Result (A - B):
 [[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
"""82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplicatio

In [37]:
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)

result = np.dot(C, D)


print("Result of Matrix Multiplication (C * D):\n", result)

Matrix C (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Matrix D (2x4):
 [[ 7  8  9 10]
 [11 12 13 14]]
Result of Matrix Multiplication (C * D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
"""83. Create a matrix `E` and find its transpose.

In [38]:
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix E:\n", E)

E_transpose = E.T
print("Transpose of Matrix E:\n", E_transpose)

Original Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
"""84. Generate a square matrix `F` and compute its determinant.

In [39]:
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix F:\n", F)

determinant_F = np.linalg.det(F)
print("Determinant of Matrix F:", determinant_F)

Matrix F:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Matrix F: -9.51619735392994e-16


In [ ]:
"""85. Create a square matrix `G` and find its inverse.

In [40]:
G = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print("Matrix G:\n", G)

try:
    G_inv = np.linalg.inv(G)
    print("Inverse of Matrix G:\n", G_inv)
except np.linalg.LinAlgError:
    print("Matrix G is singular and cannot be inverted.")

Matrix G:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of Matrix G:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
